"""vue corbeille

Revision ID: 5d504b766d7e
Revises: af33dd362731
Create Date: 2023-07-19 08:16:29.455567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d504b766d7e'
down_revision = 'af33dd362731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaires_evaluer', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('commentaires_n1', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier', schema=None) as batch_op:
        batch_op.drop_column('commentaires_n1')
        batch_op.drop_column('commentaires_evaluer')

    # ### end Alembic commands ###
