"""Initiation migration

Revision ID: 6842f506f817
Revises: 5ece801fac2e
Create Date: 2023-06-22 17:29:21.946004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6842f506f817'
down_revision = '5ece801fac2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.drop_column('confirm')

    # ### end Alembic commands ###
