"""Initiation migration

Revision ID: 6e50b003d030
Revises: 39c68e602d68
Create Date: 2023-06-20 17:03:05.232935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e50b003d030'
down_revision = '39c68e602d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
