"""Initiation migration

Revision ID: a5b3614f88f9
Revises: b7a3c328e8a7
Create Date: 2023-06-20 11:25:47.577975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5b3614f88f9'
down_revision = 'b7a3c328e8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.alter_column('validation',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.alter_column('validation',
               existing_type=sa.String(length=20),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    # ### end Alembic commands ###
