"""Initiation migration

Revision ID: aedcef278941
Revises: a5b3614f88f9
Create Date: 2023-06-20 11:33:21.534945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedcef278941'
down_revision = 'a5b3614f88f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.drop_column('validation')

    # ### end Alembic commands ###
