"""vue corbeille

Revision ID: af33dd362731
Revises: 708fa3ba37dc
Create Date: 2023-07-18 22:06:03.064109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af33dd362731'
down_revision = '708fa3ba37dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier', schema=None) as batch_op:
        batch_op.drop_column('validation')

    # ### end Alembic commands ###
