"""Initiation migration

Revision ID: b7a3c328e8a7
Revises: a9026a583cc8
Create Date: 2023-06-20 10:49:03.944821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a3c328e8a7'
down_revision = 'a9026a583cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaires', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('validation', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.drop_column('validation')
        batch_op.drop_column('commentaires')

    # ### end Alembic commands ###
