"""Initiation migration

Revision ID: d330cadc3930
Revises: 6e50b003d030
Create Date: 2023-06-21 14:00:33.549900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd330cadc3930'
down_revision = '6e50b003d030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaires_evaluer', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('commentaires_n1', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type_defauts', schema=None) as batch_op:
        batch_op.drop_column('commentaires_n1')
        batch_op.drop_column('commentaires_evaluer')

    # ### end Alembic commands ###
